<a href="https://colab.research.google.com/github/kaushik1506/ai-tech-gen-student-performance/blob/main/student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv('Student_Performance.csv')

In [44]:
df

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             25000 non-null  int64
 1   age                    25000 non-null  int64
 2   gender                 25000 non-null  object
 3   school_type            25000 non-null  object
 4   parent_education       25000 non-null  object
 5   study_hours            25000 non-null  float64
 6   attendance_percentage  25000 non-null  float64
 7   internet_access        25000 non-null  object
 8   travel_time            25000 non-null  object
 9   extra_activities       25000 non-null  object
 10  study_method           25000 non-null  object
 11  math_score             25000 non-null  float64
 12  science_score          25000 non-null  float64
 13  english_score          25000 non-null  float64
 14  overall_score          25000 non-null  float64
 15  final_grade            25000 non-null  object
dtypes: float64(6), int64(2), object(8)
memory usage: 3.1+ MB

In [46]:
df.describe()

,student_id,age,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score
count,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,7493.04380,16.482760,4.253224,75.084084,63.785944,63.745320,63.681948,64.006172
std,4323.56215,1.703895,2.167541,14.373171,20.875262,20.970529,20.792693,18.932025
min,1.00000,14.000000,0.500000,50.000000,0.000000,0.000000,0.000000,14.500000
25%,3743.75000,15.000000,2.400000,62.800000,48.300000,48.200000,48.300000,49.000000
50%,7461.50000,16.000000,4.300000,75.100000,64.100000,64.100000,64.200000,64.200000
75%,11252.00000,18.000000,6.100000,87.500000,80.000000,80.000000,80.000000,79.000000
max,15000.00000,19.000000,8.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [47]:
df['final_grade'].value_counts()

final_grade
d    6311
c    6161
e    5672
f    2955
b    2696
a    1205
Name: count, dtype: int64

In [48]:
df.isnull().sum()

student_id               0
age                      0
gender                   0
school_type              0
parent_education         0
study_hours              0
attendance_percentage    0
internet_access          0
travel_time              0
extra_activities         0
study_method             0
math_score               0
science_score            0
english_score            0
overall_score            0
final_grade              0
dtype: int64

In [49]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
le = LabelEncoder()
scaler = StandardScaler()

In [50]:
df.head()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f

In [51]:
#For nominal categorical feautures
df = pd.get_dummies(df,columns=['gender','school_type','internet_access'])
df.head()

,student_id,age,parent_education,study_hours,attendance_percentage,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade,gender_female,gender_male,gender_other,school_type_private,school_type_public,internet_access_no,internet_access_yes
0,1,14,post graduate,3.1,84.3,<15 min,yes,notes,42.7,55.4,57.0,53.1,e,False,True,False,False,True,False,True
1,2,18,graduate,3.7,87.8,>60 min,no,textbook,57.6,68.8,64.8,61.3,d,True,False,False,False,True,False,True
2,3,17,post graduate,7.9,65.5,<15 min,no,notes,84.8,95.0,79.2,89.6,b,True,False,False,True,False,True,False
3,4,16,high school,1.1,58.1,15-30 min,no,notes,44.4,27.5,54.7,41.6,e,False,False,True,False,True,True,False
4,5,16,high school,1.3,61.0,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f,True,False,False,False,True,False,True

In [52]:
#For ordinal categorical feautures
df['final_grade'] = le.fit_transform(df['final_grade'])
df.head()

,student_id,age,parent_education,study_hours,attendance_percentage,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade,gender_female,gender_male,gender_other,school_type_private,school_type_public,internet_access_no,internet_access_yes
0,1,14,post graduate,3.1,84.3,<15 min,yes,notes,42.7,55.4,57.0,53.1,4,False,True,False,False,True,False,True
1,2,18,graduate,3.7,87.8,>60 min,no,textbook,57.6,68.8,64.8,61.3,3,True,False,False,False,True,False,True
2,3,17,post graduate,7.9,65.5,<15 min,no,notes,84.8,95.0,79.2,89.6,1,True,False,False,True,False,True,False
3,4,16,high school,1.1,58.1,15-30 min,no,notes,44.4,27.5,54.7,41.6,4,False,False,True,False,True,True,False
4,5,16,high school,1.3,61.0,30-60 min,yes,group study,8.9,32.7,30.0,25.4,5,True,False,False,False,True,False,True

In [53]:
#removing unrequired feautures
df = df.drop(axis=1,columns=['student_id','age','parent_education','travel_time','study_method','extra_activities'])
df.head()

,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score,final_grade,gender_female,gender_male,gender_other,school_type_private,school_type_public,internet_access_no,internet_access_yes
0,3.1,84.3,42.7,55.4,57.0,53.1,4,False,True,False,False,True,False,True
1,3.7,87.8,57.6,68.8,64.8,61.3,3,True,False,False,False,True,False,True
2,7.9,65.5,84.8,95.0,79.2,89.6,1,True,False,False,True,False,True,False
3,1.1,58.1,44.4,27.5,54.7,41.6,4,False,False,True,False,True,True,False
4,1.3,61.0,8.9,32.7,30.0,25.4,5,True,False,False,False,True,False,True

In [55]:
#standardization for numerical data
cont_cols = ['study_hours','attendance_percentage','math_score','science_score','english_score','overall_score']
df[cont_cols] = sc.fit_transform(df[cont_cols])
df.head()

,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score,final_grade,gender_female,gender_male,gender_other,school_type_private,school_type_public,internet_access_no,internet_access_yes
0,-0.532053,0.641202,-1.010113,-0.397963,-0.321367,-0.576082,4,False,True,False,False,True,False,True
1,-0.255236,0.884716,-0.296335,0.241042,0.053772,-0.142944,3,True,False,False,False,True,False,True
2,1.682482,-0.666817,1.006669,1.490439,0.746337,1.351907,1,True,False,False,True,False,True,False
3,-1.454776,-1.181675,-0.928675,-1.728428,-0.431985,-1.183530,4,False,False,True,False,True,True,False
4,-1.362504,-0.979907,-2.629286,-1.480456,-1.619926,-2.039240,5,True,False,False,False,True,False,True